### ISSUE TITLE
FSK - Alterskontrolle

### ISSUE THREAD

**Issue by Dennis2512** [LukasBlank/KiNow#13]
- Ab welchem Alter kann man sich in der App registrieren? Kinder mit 12 dürfen bspw. noch keine Kinotickets online kaufen, das würde PayPal voraussetzen und PayPal ist erst ab 18 Jahren
- Es muss kontrolliert werden, wie alt eine Person ist (Alter wird bei der Registration angegeben). Ist eine Person bspw. unter 18 Jahren, darf diese keine Kinotickets für einen Film ab 18 Jahren kaufen

**Comment by LukasBlank** [comment]
@Dennis2512 würde sagen für die Registrierung etc muss man mindestens 18 sein, dann machen wir uns es einfach. Ggf. können wir ja später noch eine Art Reservierung erstellen die nicht online bezahlt wird und dann auch ab 16 oder so geht.

**Comment by LukasBlank** [comment]
Was sagst du dazu?

**Comment by Dennis2512** [comment]
@LukasBlank Also wenn man mal bei der Konkurrenz (Cinemaxx) schaut, muss man bei der Registrierung einen Haken setzen dass man 16 Jahre alt ist

**Comment by Dennis2512** [comment]
**CLOSED**: Absicherung durch CheckBox mit der Zustimmung der Terms of Service und mit der Zustimmung des Mindestalters von 16 Jahren reicht aus.
