### ISSUE TITLE
Username Überprüfung

### ISSUE THREAD

**Issue by Dennis2512** [LukasBlank/KiNow#14]
Bei der Registrierung gibt jeder Benutzer neben seinem Namen (welcher mehrmals in der Datenbank vorkommen kann, da mehr als eine Person bspw. Dieter Bohlen heißt) einen Username an, der **eindeutig** sein muss. Es muss bei der Registrierung abgefragt werden, ob bereits ein solcher Username in der Datenbank vorhanden ist. Wenn ja, muss dem Benutzer eine Meldung angezeigt werden, dass er einen anderen Username wählen muss, da seiner bereits vergeben ist.

**Comment by LukasBlank** [comment]
@Jeanyusjoonyer dazu müssen allen Nutzern unserer Datenbank auch noch das Attribut Username hinzugefügt werden, ansonsten kein Problem

**Comment by Dennis2512** [comment]
**CLOSED**: Username wird nicht benötigt, E-Mail mit vollständigem Namen reicht aus.
