### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by LukasBlank** [LukasBlank/KiNow#21]
Wenn sich ein Nutzer ausloggen will, dann soll er darauf hingewiesen werden, dass er noch offene Reservierungen hat die durch die Abmeldung verloren gehen (wenn dies der Fall ist) und diese sollen dann auch endgültig gelöscht werden

**Comment by LukasBlank** [comment]
Abfrage nach Bestätigung bevor diese gelöscht werden

**Comment by Dennis2512** [comment]
Kann durch einen Dialog verwirklicht werden. Den Dialog kann ich erstellen, das Backend muss ihn nur an die Stelle setzen wo er zum Einsatz kommen soll und dann auf die Buttons "OK" und "Cancel" reagieren.

**Comment by LukasBlank** [comment]
Klingt gut !

**Comment by Dennis2512** [comment]
Alert Dialog ist jetzt implementiert, was der Ja / Nein Button machen soll kann man in der AlertDialog.class definieren. Momentan beendet ein Klick auf "YES" die Anwendung, das ist aber so gewollt (nur zum ersten Testen, muss geändert werden) und kann wie gesagt in der AlertDialog.class geändert werden.

Es muss vor aufrufen des Dialoges geprüft werden, ob noch offene Bestellungen vorhanden sind. Nur wenn das der Fall ist darf der Dialog aufgerufen werden.

**Logout an sich funktioniert noch nicht**
